# Samsung Galaxy A5U (SM-A500FU) legacy Qualcomm Android boot image packaging

header_version = 0
page_size = 2048
kernel_image = "Image"
base = 0x80000000

kernel_offset = 0x00008000
ramdisk_offset = 0x01000000
second_offset = 0x00f00000
tags_offset = 0x00000100
dtb_offset = 0x0

ramdisk_size = 1
append_seandroid_enforce = true
cmdline = ""

[qcdt]
entries = [
    { msm_id = [206, 0], board_id = [0xce08ff01, 1] },
]
