use std::{collections::BTreeMap, fmt::Write, fs, path::Path};

use crate::Result;

use super::{
    KernelDevice,
    config::{self, KernelSource, KernelSourceScope},
    cpio::DEFAULT_TARGET,
    workspace_root,
};

const GENERATED_KERNEL_CI: &str = ".github/workflows/kernel-ci.generated.yml";

#[derive(clap::Args, Debug)]
pub(crate) struct CiWorkflowsArgs {
    #[arg(long)]
    check: bool,
}

#[derive(Clone, Debug)]
struct KernelCiPlan {
    primes: Vec<PrimeJob>,
    devices: Vec<DeviceJob>,
}

#[derive(Clone, Debug)]
struct PrimeJob {
    id: String,
    cache_id: String,
    name: String,
    target: String,
    source: KernelSource,
}

#[derive(Clone, Debug)]
struct DeviceJob {
    id: String,
    name: String,
    artifact: String,
    device: String,
    source_id: String,
    source: KernelSource,
    cpio_target: String,
    bootimg: bool,
    prime_id: Option<String>,
}

pub(crate) fn run(args: CiWorkflowsArgs) -> Result<()> {
    ci_workflows(args)
}

fn ci_workflows(args: CiWorkflowsArgs) -> Result<()> {
    let workspace_root = workspace_root()?;
    let output = generated_kernel_ci(&workspace_root)?;
    let path = workspace_root.join(GENERATED_KERNEL_CI);

    if args.check {
        let existing = fs::read_to_string(&path)
            .map_err(|err| format!("read generated workflow {}: {err}", path.display()))?;
        if existing == output {
            println!("generated workflows are current");
            return Ok(());
        }
        return Err(format!(
            "generated workflow is stale: {}\nrun `cargo xtask ci-workflows` and commit the result",
            path.display()
        ));
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| format!("create {}: {err}", parent.display()))?;
    }
    fs::write(&path, output).map_err(|err| format!("write {}: {err}", path.display()))?;
    println!("wrote {}", path.display());
    Ok(())
}

fn generated_kernel_ci(workspace_root: &Path) -> Result<String> {
    let plan = kernel_ci_plan(workspace_root)?;
    let mut output = String::new();
    writeln!(
        output,
        "# This file is generated by `cargo xtask ci-workflows`. Do not edit by hand."
    )
    .unwrap();
    output.push_str("name: Kernel CI\n\n");
    output.push_str("on:\n");
    output.push_str("  workflow_call:\n");
    output.push_str("    inputs:\n");
    output.push_str("      image:\n");
    output.push_str("        required: true\n");
    output.push_str("        type: string\n\n");
    output.push_str("permissions:\n");
    output.push_str("  contents: read\n");
    output.push_str("  packages: read\n\n");
    output.push_str("env:\n");
    output.push_str("  CARGO_TERM_COLOR: always\n\n");
    output.push_str("jobs:\n");

    if plan.primes.is_empty() && plan.devices.is_empty() {
        write_noop_job(&mut output);
        return Ok(output);
    }

    for prime in &plan.primes {
        write_prime_job(&mut output, prime);
    }
    for device in &plan.devices {
        write_device_job(&mut output, device);
    }

    Ok(output)
}

fn kernel_ci_plan(workspace_root: &Path) -> Result<KernelCiPlan> {
    let mut primes = BTreeMap::<String, PrimeJob>::new();
    let mut devices = Vec::new();

    for device in configured_devices(workspace_root)? {
        let device_config = config::load_device_config(workspace_root, &device)?;
        let Some(source) = device_config.kernel_source.clone() else {
            continue;
        };
        let source_id = sanitize(&source.identity.id);
        let prime_id = match source.scope {
            KernelSourceScope::Default | KernelSourceScope::Soc => {
                let prime = prime_job(&source)?;
                let prime_id = prime.id.clone();
                match primes.get(&prime_id) {
                    Some(existing) if existing.source != source => {
                        return Err(format!(
                            "kernel source collision for generated CI job {prime_id}"
                        ));
                    }
                    Some(_) => {}
                    None => {
                        primes.insert(prime_id.clone(), prime);
                    }
                }
                Some(prime_id)
            }
            KernelSourceScope::Device => None,
        };

        let device_id = device.id();
        devices.push(DeviceJob {
            id: format!("kernel-{}", sanitize(&device_id)),
            name: device_id.clone(),
            artifact: format!("kernel-{}", sanitize(&device_id)),
            device: device_id,
            source_id,
            source,
            cpio_target: device_config
                .cpio
                .target
                .unwrap_or_else(|| DEFAULT_TARGET.to_string()),
            bootimg: device_config.bootimg.is_some(),
            prime_id,
        });
    }

    Ok(KernelCiPlan {
        primes: primes.into_values().collect(),
        devices,
    })
}

fn prime_job(source: &KernelSource) -> Result<PrimeJob> {
    match source.scope {
        KernelSourceScope::Default => Ok(PrimeJob {
            id: "prime-default".to_string(),
            cache_id: sanitize(&source.identity.id),
            name: format!("{} prime", source.identity.label),
            target: source.identity.id.clone(),
            source: source.clone(),
        }),
        KernelSourceScope::Soc => Ok(PrimeJob {
            id: format!("prime-{}", sanitize(&source.identity.id)),
            cache_id: sanitize(&source.identity.id),
            name: format!("{} prime", source.identity.label),
            target: source.identity.id.clone(),
            source: source.clone(),
        }),
        KernelSourceScope::Device => {
            Err("device-scoped sources do not have prime jobs".to_string())
        }
    }
}

fn write_noop_job(output: &mut String) {
    output.push_str("  noop:\n");
    output.push_str("    name: No kernel builds\n");
    output.push_str("    runs-on: ubuntu-latest\n");
    output.push_str("    steps:\n");
    output.push_str("      - run: echo 'No configured kernel builds'\n");
}

fn write_prime_job(output: &mut String, prime: &PrimeJob) {
    writeln!(output, "  {}:", prime.id).unwrap();
    writeln!(output, "    name: {}", prime.name).unwrap();
    write_common_job_header(output);
    write_kernel_env(output);
    output.push_str("    steps:\n");
    write_checkout_step(output);
    write_restore_ccache_step(
        output,
        "Restore source ccache",
        &source_cache_key(&prime.cache_id, &prime.source),
        None,
    );
    write_configure_ccache_step(output);
    output.push_str("      - name: Prime kernel ccache\n");
    writeln!(
        output,
        "        run: cargo xtask kernel-prime {}",
        shell_quote(&prime.target)
    )
    .unwrap();
    write_show_ccache_step(output);
    write_save_ccache_step(
        output,
        "Save source ccache for device jobs",
        &source_cache_key(&prime.cache_id, &prime.source),
    );
}

fn write_device_job(output: &mut String, device: &DeviceJob) {
    writeln!(output, "  {}:", device.id).unwrap();
    writeln!(output, "    name: {}", device.name).unwrap();
    if let Some(prime_id) = &device.prime_id {
        output.push_str("    needs:\n");
        writeln!(output, "      - {prime_id}").unwrap();
    }
    write_common_job_header(output);
    write_kernel_env(output);
    output.push_str("    steps:\n");
    write_checkout_step(output);
    output.push_str("      - name: Set up Rust cache\n");
    output.push_str("        uses: actions-rust-lang/setup-rust-toolchain@v1\n");
    output.push_str("        with:\n");
    output.push_str("          components: rust-src,rustfmt\n");
    writeln!(output, "          target: {}", device.cpio_target).unwrap();
    output.push_str("          rustflags: \"\"\n");
    writeln!(
        output,
        "          cache-shared-key: pocketboot-kernel-{}-df-${{{{ hashFiles('.github/Dockerfile') }}}}",
        sanitize(&device.cpio_target)
    )
    .unwrap();
    output.push_str("          cache-bin: false\n");
    output.push_str("          cache-on-failure: true\n");
    let device_key = device_cache_key(device);
    let source_key = source_cache_key(&device.source_id, &device.source);
    write_restore_ccache_step(
        output,
        "Restore device or source ccache",
        &device_key,
        Some(&source_key),
    );
    write_configure_ccache_step(output);
    output.push_str("      - name: Build kernel and boot image\n");
    output.push_str("        run: |\n");
    writeln!(
        output,
        "          cargo xtask kernel {}",
        shell_quote(&device.device)
    )
    .unwrap();
    if device.bootimg {
        writeln!(
            output,
            "          cargo xtask bootimg {}",
            shell_quote(&device.device)
        )
        .unwrap();
    }
    write_show_ccache_step(output);
    write_save_ccache_step(output, "Save device ccache", &device_key);
    output.push_str("      - name: Upload boot artifacts\n");
    output.push_str("        uses: actions/upload-artifact@v4\n");
    output.push_str("        with:\n");
    writeln!(output, "          name: {}", device.artifact).unwrap();
    output.push_str("          path: |\n");
    writeln!(
        output,
        "            target/kernel/{}/boot.img",
        device.device
    )
    .unwrap();
    writeln!(
        output,
        "            target/kernel/{}/.config",
        device.device
    )
    .unwrap();
    writeln!(
        output,
        "            target/kernel/{}/arch/arm/boot/Image.gz",
        device.device
    )
    .unwrap();
    writeln!(
        output,
        "            target/kernel/{}/arch/arm/boot/dts/**/*.dtb",
        device.device
    )
    .unwrap();
    writeln!(
        output,
        "            target/kernel/{}/arch/arm64/boot/Image.gz",
        device.device
    )
    .unwrap();
    writeln!(
        output,
        "            target/kernel/{}/arch/arm64/boot/dts/**/*.dtb",
        device.device
    )
    .unwrap();
    output.push_str("          if-no-files-found: error\n");
    output.push_str("          include-hidden-files: true\n");
}

fn write_common_job_header(output: &mut String) {
    output.push_str("    runs-on: ubuntu-latest\n");
    output.push_str("    timeout-minutes: 120\n");
    output.push_str("    container:\n");
    output.push_str("      image: ${{ inputs.image }}\n");
    output.push_str("      credentials:\n");
    output.push_str("        username: ${{ github.actor }}\n");
    output.push_str("        password: ${{ secrets.GITHUB_TOKEN }}\n");
}

fn write_kernel_env(output: &mut String) {
    output.push_str("    env:\n");
    output.push_str("      CCACHE_BASEDIR: ${{ github.workspace }}\n");
    output.push_str("      CCACHE_COMPILERCHECK: content\n");
    output.push_str("      CCACHE_DIR: ${{ github.workspace }}/target/ccache\n");
    output.push_str("      CCACHE_MAXSIZE: 2G\n");
    output.push_str("      HOSTCC: ccache gcc\n");
}

fn write_checkout_step(output: &mut String) {
    output.push_str("      - name: Checkout pocketboot\n");
    output.push_str("        uses: actions/checkout@v4\n");
    output.push_str("        with:\n");
    output.push_str(
        "          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}\n",
    );
    output.push_str("          ref: ${{ github.event.pull_request.head.sha || github.sha }}\n");
    output.push_str("          persist-credentials: false\n");
}

fn write_restore_ccache_step(output: &mut String, name: &str, key: &str, fallback: Option<&str>) {
    writeln!(output, "      - name: {name}").unwrap();
    output.push_str("        uses: actions/cache/restore@v4\n");
    output.push_str("        with:\n");
    output.push_str("          path: target/ccache\n");
    writeln!(output, "          key: {key}").unwrap();
    output.push_str("          restore-keys: |\n");
    if let Some(fallback) = fallback {
        writeln!(output, "            {fallback}").unwrap();
    }
    writeln!(output, "            {}", cache_prefix(key)).unwrap();
    if let Some(fallback) = fallback {
        writeln!(output, "            {}", cache_prefix(fallback)).unwrap();
    }
}

fn write_configure_ccache_step(output: &mut String) {
    output.push_str("      - name: Configure ccache\n");
    output.push_str("        run: |\n");
    output.push_str("          ccache --set-config=max_size=\"$CCACHE_MAXSIZE\"\n");
    output.push_str("          ccache --zero-stats\n");
}

fn write_show_ccache_step(output: &mut String) {
    output.push_str("      - name: Show ccache stats\n");
    output.push_str("        if: always()\n");
    output.push_str("        run: ccache --show-stats\n");
}

fn write_save_ccache_step(output: &mut String, name: &str, key: &str) {
    writeln!(output, "      - name: {name}").unwrap();
    output.push_str("        if: always()\n");
    output.push_str("        uses: actions/cache/save@v4\n");
    output.push_str("        with:\n");
    output.push_str("          path: target/ccache\n");
    writeln!(output, "          key: {key}").unwrap();
}

fn source_cache_key(id: &str, source: &KernelSource) -> String {
    cache_key("source", id, &source.sha)
}

fn device_cache_key(device: &DeviceJob) -> String {
    cache_key("device", &device.id, &device.source.sha)
}

fn cache_key(kind: &str, id: &str, sha: &str) -> String {
    format!(
        "${{{{ runner.os }}}}-kernel-ccache-{kind}-{id}-{sha}-${{{{ hashFiles('.github/Dockerfile') }}}}-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}"
    )
}

fn cache_prefix(key: &str) -> &str {
    key.rsplit_once("-${{ github.run_id }}-${{ github.run_attempt }}")
        .map_or(key, |(prefix, _)| prefix)
}

fn configured_devices(workspace_root: &Path) -> Result<Vec<KernelDevice>> {
    let root = workspace_root.join("configs/device");
    let mut devices = Vec::new();
    for vendor in read_dir(&root, "device config vendor directory")? {
        if !vendor
            .file_type()
            .map_err(|err| format!("read file type for {}: {err}", vendor.path().display()))?
            .is_dir()
        {
            continue;
        }
        let vendor_name = vendor
            .file_name()
            .into_string()
            .map_err(|name| format!("device vendor is not valid UTF-8: {name:?}"))?;
        for device in read_dir(&vendor.path(), "device config directory")? {
            if !device
                .file_type()
                .map_err(|err| format!("read file type for {}: {err}", device.path().display()))?
                .is_file()
            {
                continue;
            }
            let path = device.path();
            if path.extension().and_then(|extension| extension.to_str()) != Some("toml") {
                continue;
            }
            let stem = path
                .file_stem()
                .and_then(|stem| stem.to_str())
                .ok_or_else(|| {
                    format!("device config path is not valid UTF-8: {}", path.display())
                })?;
            devices.push(KernelDevice::parse(&format!("{vendor_name}/{stem}"))?);
        }
    }
    devices.sort_by_key(KernelDevice::id);
    Ok(devices)
}

fn read_dir(path: &Path, description: &str) -> Result<Vec<fs::DirEntry>> {
    let entries = fs::read_dir(path)
        .map_err(|err| format!("read {description} {}: {err}", path.display()))?;
    entries
        .map(|entry| entry.map_err(|err| format!("read {description} {}: {err}", path.display())))
        .collect()
}

fn sanitize(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || matches!(ch, '-' | '_') {
                ch
            } else {
                '-'
            }
        })
        .collect()
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}
