name = "Samsung Galaxy Express GT-I8730"

[kernel-source]
# samsung-expressltexx-mainlining's Linux gitlink / samsung-expressltexx branch.
remote = "https://github.com/samcday/linux.git"
sha = "3bc07d096bddd33218b8c13b9fa30ffdaba3c050"

[kernel]
dtb_stem = "qcom-msm8930-samsung-expressltexx"

[cpio]
target = "armv7-unknown-linux-musleabihf"

[kconfig]
# PM8917's direct L31 rail powers maXTouch; it is not an RPM regulator.
REGULATOR_QCOM_PM8917 = true
TOUCHSCREEN_ATMEL_MXT = true
I2C_GPIO = true
NEW_LEDS = true
LEDS_CLASS = true
KEYBOARD_TM2_TOUCHKEY = true

[bootimg]
header_version = 0
page_size = 2048
kernel_image = "zImage"
base = 0x80200000
kernel_offset = 0x00008000
ramdisk_offset = 0x02200000
second_offset = 0x00f00000
tags_offset = 0x02000000
dtb_offset = 0x0
append_dtb = true
cmdline = ""
